# Generated by Django 3.1.5 on 2021-01-27 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
                ('nr_telefonu', models.IntegerField()),
                ('wlasciciel', models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dystans', models.FloatField()),
                ('cena_lokalizacja', models.FloatField()),
            ],
            options={
                'ordering': ('dystans',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_potrawyMenu', models.CharField(max_length=45)),
                ('cenaMenu', models.FloatField()),
            ],
            options={
                'ordering': ('nazwa_potrawyMenu',),
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_potrawy', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
                ('koszt', models.FloatField()),
                ('data_zamoienia', models.DateField()),
                ('Klient_Zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dostawa.klient')),
                ('Lokalizacja_Zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dostawa.lokalizacja')),
            ],
            options={
                'ordering': ('nazwa_potrawy',),
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_Platnosci', models.CharField(choices=[('K', 'Karta'), ('G', 'Gotowka'), ('B', 'Blik')], default='Brak', max_length=1)),
                ('kwota', models.FloatField()),
                ('Klient_Platnosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dostawa.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Catering_dietetyczny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=45)),
                ('liczba', models.IntegerField()),
                ('liczba_kalori', models.IntegerField()),
                ('cena', models.FloatField()),
                ('Zamowienie_Catering_dieteyczny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dostawa.zamowienie')),
            ],
            options={
                'ordering': ('rodzaj',),
            },
        ),
    ]
