# Generated by Django 3.1.5 on 2021-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostawa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokalizacja',
            name='cena_lokalizacja',
            field=models.FloatField(null=True),
        ),
    ]
