# Generated by Django 3.1.5 on 2021-01-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dostawa', '0002_auto_20210127_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering_dietetyczny',
            name='Zamowienie_Catering_dieteyczny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dostawa.zamowienie'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='miasto',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_telefonu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='ulica',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cenaMenu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nazwa_potrawyMenu',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
